<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\D47.Core\D47.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="D47.App.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Whisper.net" Version="1.9.1" />

    <PackageReference Include="Whisper.net.Runtime" Version="1.9.1" />

    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.9.1" />
  </ItemGroup>

</Project>
