<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\D47.Core\D47.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="D47.Tts.Tests" />
  </ItemGroup>

</Project>
