namespace D47.Core.Knowledge;

/// <summary>
/// One group of materials a High Grade Emission can hold, and the condition that produces it.
/// </summary>
/// <param name="Allegiance">
/// The allegiance the <b>system</b> answers to, exactly as the journal spells it —
/// <c>Federation</c>, <c>Empire</c>, <c>Independent</c>. <b>Never null</b>: every group names one,
/// including the four that also name states.
/// </param>
/// <param name="States">
/// The states the <b>controlling faction</b> must be in — any one of them — in the journal's own
/// spelling. Empty for the two groups that are about allegiance alone.
/// </param>
/// <param name="Materials">The material symbols, as the journal writes them.</param>
public sealed record EmissionGroup(
    string Allegiance,
    IReadOnlyList<string> States,
    IReadOnlyList<string> Materials);

/// <summary>
/// What a High Grade Emission holds, and where (list.md Phase 40).
/// <para>
/// <b>This table is the Commander's, given 2026-08-21, and it supersedes what was derived from the
/// sources.</b> Two published readings were tried before it and both shipped wrong, so what is
/// written down here is the corrected table rather than the research that led to it —
/// <c>docs/plans/change-requests.md</c> item 22 keeps the sources and the trail.
/// </para>
/// <para>
/// <b>Every group is allegiance + population, and four of them add a state.</b> There is no
/// "superpower beats state" rule any more because no group needs one: the superpower groups are
/// Federal and Imperial, the state groups are all <b>Independent</b>, and nothing overlaps. An
/// <b>Alliance</b> system yields nothing at all, which is a real exclusion and is taken as written.
/// </para>
/// <para>
/// <b>The state is the controlling faction's</b> — the journal's <c>SystemFaction</c> — and not any
/// faction's. Two earlier readings got this wrong in opposite directions: the first made both
/// allegiance and state per-faction, which had Federal composites announced in <b>Oppi</b>, an
/// Independent system holding one Federal faction of seven; the correction moved allegiance to the
/// system and left states per faction, which was still half wrong.
/// </para>
/// <para>
/// <b>Several materials at once survives, from one faction wearing several states.</b> A controlling
/// faction's <c>ActiveStates</c> is a list, and in the corpus it genuinely holds pairs —
/// <c>CivilUnrest + Expansion</c>, <c>Expansion + War</c>, <c>Boom + Expansion</c> — so one system
/// can offer two unrelated groups. It no longer comes from two <em>factions</em>, which is what the
/// previous reading rested it on.
/// </para>
/// <para>
/// <b>Sourced, corroborated, and then checked against the shipped table.</b> The conditions are the
/// Elite Dangerous Wiki's <i>High Grade Emissions</i> page, corroborated by the Frontier Forums
/// guide <i>Unidentified Signal Sources: A Complete Guide</i> (2017, edited 2018) — which is the
/// primary community research the rest of it descends from — and by the six filter groups
/// <c>edgalaxy.net/hge</c> sorts live EDDN detections into. <c>docs/plans/change-requests.md</c>
/// item 22 records all three, and the four places the first two disagree.
/// </para>
/// <para>
/// <b>It is not hand-written game data, and that distinction is the point.</b>
/// <c>Materials.tsv</c> is generated by <c>tools/gen-materials.py</c> and already carries these
/// conditions in its origins column — "Signal source (High grade emissions, Boom)" and the rest
/// — for all ten materials below. <see cref="Groups"/> is the same facts in a shape a callout can
/// use, and a test asserts the two agree material for material, so a regenerated table that
/// disagrees with this fails rather than drifting. That is the same two-source assertion the
/// engineer distances and the lore resolvers already carry.
/// </para>
/// <para>
/// <b>Three rulings the sources left open</b>, all settled by the Commander on 2026-08-21 and all
/// recorded here because a table that hides its choices is one nobody can check later:
/// Proprietary Composites <em>is</em> included beside Core Dynamics Composites; the Proto
/// materials are <b>Boom only</b> and not Expansion or Investment; and the population floor is
/// <b>always</b> applied rather than only to Outbreak.
/// </para>
/// </summary>
public static class EmissionRules
{
    /// <summary>
    /// The population a system needs before a High Grade Emission is worth mentioning at all.
    /// <para>
    /// <b>A condition of every group</b>, stated as such in the Commander's own table: each row
    /// reads <i>allegiance + high pop</i>, with a state on four of them. So a sparsely populated
    /// system says nothing whatever else is true of it.
    /// </para>
    /// </summary>
    public const long MinimumPopulation = 1_000_000;

    /// <summary>
    /// The six groups, exactly as the Commander wrote them.
    /// <para>
    /// <b>Order no longer disambiguates anything</b> — the groups do not overlap, so it is merely
    /// the order things are said in. It used to be a reconstruction of a hidden rank, which the
    /// superseded reading needed and this one does not.
    /// </para>
    /// </summary>
    public static readonly IReadOnlyList<EmissionGroup> Groups =
    [
        new("Federation", [], ["fedcorecomposites", "fedproprietarycomposites"]),
        new("Empire", [], ["imperialshielding"]),
        new("Independent", ["CivilUnrest"], ["improvisedcomponents"]),
        new("Independent", ["War", "CivilWar"], ["militarygradealloys", "militarysupercapacitors"]),

        // Expansion beside Boom. The Commander ruled Boom-only that morning, against the wiki, and
        // corrected it the same day — and it is not a small widening: Expansion is the second
        // commonest faction state in the corpus after None.
        new("Independent", ["Boom", "Expansion"],
            ["protoheatradiators", "protolightalloys", "protoradiolicalloys"]),

        new("Independent", ["Outbreak"], ["pharmaceuticalisolators"]),
    ];

    /// <summary>
    /// Every group a system offers — none, one, or two where its controlling faction wears two
    /// states at once.
    /// <para>
    /// <paramref name="systemAllegiance"/> is <b>the system's</b>: the journal's
    /// <c>SystemAllegiance</c>. <paramref name="states"/> is <b>the controlling faction's</b> —
    /// its <c>FactionState</c> and its <c>ActiveStates</c> together. Both parameters are named for
    /// what they are because both have been passed the wrong thing once.
    /// </para>
    /// <para>
    /// <b>Several rather than one.</b> This used to answer a single group, which suited a table
    /// where the groups competed; in the Commander's table they do not, and a faction in
    /// <c>Expansion + War</c> really does offer the Proto materials and the Military ones.
    /// </para>
    /// <para>
    /// Population is not checked here — it is not a property of a group, it is a property of the
    /// system, and <see cref="MinimumPopulation"/> is the caller's to apply.
    /// </para>
    /// </summary>
    public static IReadOnlyList<EmissionGroup> For(string? systemAllegiance, IEnumerable<string>? states)
    {
        if (systemAllegiance is not { Length: > 0 })
        {
            return [];
        }

        var held = (states ?? [])
            .Where(state => !string.IsNullOrWhiteSpace(state))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        return
        [
            .. Groups.Where(group =>
                string.Equals(group.Allegiance, systemAllegiance, StringComparison.OrdinalIgnoreCase)
                && (group.States.Count == 0 || group.States.Any(held.Contains))),
        ];
    }

    /// <summary>
    /// What one material needs, or null for one no emission carries. The other direction of
    /// <see cref="Groups"/>, so a caller looking for a place to find something asks the same table
    /// the callout answers from rather than deriving its own.
    /// </summary>
    public static EmissionGroup? Holding(string? symbol) =>
        symbol is { Length: > 0 }
            ? Groups.FirstOrDefault(group =>
                group.Materials.Any(material =>
                    string.Equals(material, symbol, StringComparison.OrdinalIgnoreCase)))
            : null;
}
