namespace D47.Core.Knowledge;

/// <summary>
/// One group of materials a High Grade Emission can hold, and the condition that produces it.
/// </summary>
/// <param name="Allegiance">
/// The superpower the owning faction answers to, or null for a condition that is about a state
/// instead. <c>Federation</c> and <c>Empire</c> exactly as the journal spells them.
/// </param>
/// <param name="States">
/// The faction states that produce this group, in the journal's own spelling — <c>Boom</c>,
/// <c>CivilWar</c>. Empty for an allegiance condition.
/// </param>
/// <param name="Materials">The material symbols, as the journal writes them.</param>
public sealed record EmissionGroup(
    string? Allegiance,
    IReadOnlyList<string> States,
    IReadOnlyList<string> Materials);

/// <summary>
/// What a High Grade Emission holds, and where (list.md Phase 40).
/// <para>
/// <b>The mechanic first, because it is what makes the rest predictable.</b> A signal is assigned
/// to <em>one faction</em>, and its contents come from that faction — not from the system. So a
/// system is evaluated a faction at a time, and one holding an Independent faction in Boom beside
/// a Federal one offers two entirely unrelated groups at once. That is ordinary rather than
/// exotic: 84 of 400 recent jumps in the corpus are into systems mixing a Federal faction with an
/// Independent or Alliance one.
/// </para>
/// <para>
/// <b>Superpower beats state, and never the other way.</b> A Federation or Imperial faction yields
/// composites or shielding respectively <em>and nothing else</em>, whatever state it is in. This is
/// the single ruling the two sources disagree about — the 2017 forums guide says an Imperial system
/// in Outbreak gives shielding and isolators together — and it is settled the wiki's way on the
/// Commander's instruction (2026-08-21), because the wiki is newer and because its reading is the
/// one consistent with the rank-order mechanic it also states.
/// </para>
/// <para>
/// <b>Sourced, corroborated, and then checked against the shipped table.</b> The conditions are the
/// Elite Dangerous Wiki's <i>High Grade Emissions</i> page, corroborated by the Frontier Forums
/// guide <i>Unidentified Signal Sources: A Complete Guide</i> (2017, edited 2018) — which is the
/// primary community research the rest of it descends from — and by the six filter groups
/// <c>edgalaxy.net/hge</c> sorts live EDDN detections into. <c>docs/plans/change-requests.md</c>
/// item 22 records all three, and the four places the first two disagree.
/// </para>
/// <para>
/// <b>It is not hand-written game data, and that distinction is the point.</b>
/// <c>Materials.tsv</c> is generated by <c>tools/gen-materials.py</c> and already carries these
/// conditions in its origins column — "Signal source (High grade emissions, Boom)" and the rest
/// — for all ten materials below. <see cref="Groups"/> is the same facts in a shape a callout can
/// use, and a test asserts the two agree material for material, so a regenerated table that
/// disagrees with this fails rather than drifting. That is the same two-source assertion the
/// engineer distances and the lore resolvers already carry.
/// </para>
/// <para>
/// <b>Three rulings the sources left open</b>, all settled by the Commander on 2026-08-21 and all
/// recorded here because a table that hides its choices is one nobody can check later:
/// Proprietary Composites <em>is</em> included beside Core Dynamics Composites; the Proto
/// materials are <b>Boom only</b> and not Expansion or Investment; and the population floor is
/// <b>always</b> applied rather than only to Outbreak.
/// </para>
/// </summary>
public static class EmissionRules
{
    /// <summary>
    /// The population a system needs before a High Grade Emission is worth mentioning at all.
    /// <para>
    /// <b>Applied to every group rather than to Outbreak alone.</b> The wiki attaches it to
    /// Pharmaceutical Isolators and states separately that emissions are commonest in systems of a
    /// million or more; the Commander's ruling is that it is a condition of all of them. So a
    /// sparsely populated system in Boom says nothing, which is the outcome that matches what a
    /// Commander actually finds when they go and look.
    /// </para>
    /// </summary>
    public const long MinimumPopulation = 1_000_000;

    /// <summary>
    /// The six groups, <b>in the wiki's stated rank order</b>. Order is load-bearing: where a
    /// faction meets more than one condition Elite picks between them by a rank nobody has seen,
    /// and this is the community's best reconstruction of it. The two allegiance groups lead,
    /// which is the same claim as superpower beating state.
    /// </summary>
    public static readonly IReadOnlyList<EmissionGroup> Groups =
    [
        new("Federation", [], ["fedcorecomposites", "fedproprietarycomposites"]),
        new("Empire", [], ["imperialshielding"]),
        new(null, ["CivilUnrest"], ["improvisedcomponents"]),
        new(null, ["War", "CivilWar"], ["militarygradealloys", "militarysupercapacitors"]),
        new(null, ["Boom"], ["protoheatradiators", "protolightalloys", "protoradiolicalloys"]),
        new(null, ["Outbreak"], ["pharmaceuticalisolators"]),
    ];

    /// <summary>
    /// What one faction's emissions would hold, or null for a faction that produces none.
    /// <para>
    /// <paramref name="states"/> is every state the faction is actually in — the journal's
    /// <c>ActiveStates</c> alongside its headline <c>FactionState</c> — because a faction in
    /// several at once is a real thing and the headline reports only one of them.
    /// </para>
    /// </summary>
    public static EmissionGroup? For(string? allegiance, IEnumerable<string>? states)
    {
        // Superpower first and then stop. A Federal or Imperial faction never yields anything but
        // its own composites or shielding, whatever else is true of it.
        if (Groups.FirstOrDefault(group =>
                group.Allegiance is { } superpower
                && string.Equals(superpower, allegiance, StringComparison.OrdinalIgnoreCase)) is { } owned)
        {
            return owned;
        }

        if (states is null)
        {
            return null;
        }

        var held = states
            .Where(state => !string.IsNullOrWhiteSpace(state))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        // In rank order, so a faction in both Boom and Civil Unrest answers with the higher of the
        // two rather than with whichever the journal happened to list first.
        return Groups.FirstOrDefault(group =>
            group.Allegiance is null && group.States.Any(held.Contains));
    }
}
