using System.Reflection;

namespace D47.Core.Knowledge;

/// <summary>Where one pad lies in a ring station: segment 1 to 12 around the ring, depth 0 to 4 from the entrance, size 1 to 3.</summary>
public readonly record struct LandingPad(int Number, int Segment, int Depth, int Size)
{
    /// <summary>The clock hour, seen entering with the green lights on the right: segment 1 is six o'clock, each segment after it one hour further round.</summary>
    public int Hour => (Segment + 4) % 12 + 1;
}

/// <summary>The shipped pad layout shared by Coriolis, Orbis, Ocellus and asteroid bases, generated by <c>tools/gen-landing-pads.py</c>.</summary>
public static class LandingPads
{
    private const string ResourceName = "D47.Core.LandingPads";

    private static readonly Lazy<Dictionary<int, LandingPad>> Loaded =
        new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    public static IReadOnlyCollection<LandingPad> All => Loaded.Value.Values;

    /// <summary>Whether a <c>StationType</c> has the ring layout.</summary>
    public static bool IsRing(string? stationType) =>
        stationType is "Coriolis" or "Orbis" or "Ocellus" or "Bernal" or "AsteroidBase";

    public static LandingPad? Find(int number) =>
        Loaded.Value.TryGetValue(number, out var pad) ? pad : null;

    private static Dictionary<int, LandingPad> Load()
    {
        var pads = new Dictionary<int, LandingPad>();

        using var stream = typeof(LandingPads).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName);

        if (stream is null)
        {
            return pads;
        }

        using var reader = new StreamReader(stream);

        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            var cells = line.Split('\t');

            if (cells.Length == 4
                && int.TryParse(cells[0], out var number)
                && int.TryParse(cells[1], out var segment)
                && int.TryParse(cells[2], out var depth)
                && int.TryParse(cells[3], out var size))
            {
                pads[number] = new LandingPad(number, segment, depth, size);
            }
        }

        return pads;
    }
}
