using System.Reflection;

namespace D47.Core.Knowledge;

/// <summary>
/// The shipped table of permit-locked systems, generated by <c>tools/gen-permits.py</c>. The station
/// index carries no permit field, so this is the only thing that can answer for a market (#310).
/// </summary>
public static class PermitSystemTable
{
    private const string ResourceName = "D47.Core.PermitSystems";

    private static readonly Lazy<HashSet<string>> Loaded =
        new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    public static IReadOnlyCollection<string> Names => Loaded.Value;

    /// <summary>Whether entering this system needs a permit. Matched on the index's own spelling.</summary>
    public static bool Locked(string? system) =>
        system is { Length: > 0 } named && Loaded.Value.Contains(named);

    private static HashSet<string> Load()
    {
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        using var stream = typeof(PermitSystemTable).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName);

        if (stream is null)
        {
            return names;
        }

        using var reader = new StreamReader(stream);

        while (reader.ReadLine() is { } line)
        {
            if (line.Length > 0 && line[0] != '#')
            {
                names.Add(line);
            }
        }

        return names;
    }
}
