using System.Globalization;
using System.Reflection;

namespace D47.Core.Knowledge;

public enum PowerplayRewardKind
{
    Decal,
    CarePackage,
    RebuyOwnTerritory,
    RebuyRival,
    Perk,
    Module,
}

/// <summary>One reward a Power grants at a rank. <see cref="Value"/> is a perk's or rebuy's signed cumulative percent.</summary>
public sealed record PowerplayReward(
    string Power,
    int Rank,
    int Merits,
    PowerplayRewardKind Kind,
    string Subject,
    int? Value);

/// <summary>The shipped table of Powerplay rank rewards, generated by <c>tools/gen-powerplay.py</c>.</summary>
public static class PowerplayRanks
{
    private const string ResourceName = "D47.Core.PowerplayRanks";

    /// <summary>The table lists ranks 1 to this; every rank past it gives a full care package.</summary>
    public const int LastTabulatedRank = 100;

    private static readonly IReadOnlyDictionary<string, string> PerkLabels =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["trade_sales"] = "trade profits on sales",
            ["rare_goods_sales"] = "profits on rare goods sales",
            ["faction_reputation"] = "minor faction reputation gain",
            ["bounty_payouts"] = "bounty payouts",
            ["weapon_module_cost"] = "weapon module cost",
            ["rearm_prices"] = "rearm prices",
            ["rearm_refuel_repair_prices"] = "rearm, refuel and repair prices",
            ["exploration_data_sales"] = "exploration data sales",
            ["organics_data_sales"] = "organics data sales",
            ["technology_profits"] = "technology commodity profits",
            ["mining_profits"] = "mining commodity profits",
            ["imperial_slaves_profits"] = "Imperial slaves commodity profits",
            ["salvage_profits"] = "salvage profits",
            ["food_medicine_profits"] = "food and medicine profits",
            ["search_rescue_payouts"] = "search and rescue payouts",
            ["black_market_profits"] = "black market profits",
            ["bounties_on_you"] = "bounties placed on you",
        };

    private static readonly Lazy<Table> Loaded =
        new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    /// <summary>The Powers in the table, spelled as the journal spells them.</summary>
    public static IReadOnlyList<string> Powers => Loaded.Value.Powers;

    /// <summary>A Power's rewards in rank order; empty for a Power the table does not know. The name is matched ignoring case.</summary>
    public static IReadOnlyList<PowerplayReward> RewardsFor(string? power) =>
        power is not null && Loaded.Value.ByPower.TryGetValue(power, out var rewards) ? rewards : [];

    /// <summary>The rank at which the Power unlocks this entitlement symbol, or null.</summary>
    public static int? RankUnlocking(string? power, string? entitlement) =>
        entitlement is null
            ? null
            : RewardsFor(power)
                .Where(r => r.Kind == PowerplayRewardKind.Module
                    && string.Equals(r.Subject, entitlement, StringComparison.OrdinalIgnoreCase))
                .Select(r => (int?)r.Rank)
                .FirstOrDefault();

    /// <summary>The cumulative merits a rank needs, or null outside 1 to <see cref="LastTabulatedRank"/>. Every Power shares one ladder.</summary>
    public static int? MeritsNeeded(int rank) =>
        Loaded.Value.Merits.TryGetValue(rank, out var merits) ? merits : null;

    public static bool GivesFullCarePackage(int rank) => rank > LastTabulatedRank;

    /// <summary>The words a perk is spoken as, or null for a key without a label.</summary>
    public static string? PerkLabel(string? key) =>
        key is not null && PerkLabels.TryGetValue(key, out var label) ? label : null;

    private static Table Load()
    {
        var byPower = new Dictionary<string, IReadOnlyList<PowerplayReward>>(StringComparer.OrdinalIgnoreCase);
        var merits = new Dictionary<int, int>();
        var powers = new List<string>();

        using var stream = typeof(PowerplayRanks).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName);

        if (stream is null)
        {
            return new Table(powers, byPower, merits);
        }

        var rows = new Dictionary<string, List<PowerplayReward>>(StringComparer.OrdinalIgnoreCase);

        using var reader = new StreamReader(stream);
        var header = true;

        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            if (header)
            {
                header = false;
                continue;
            }

            var cells = line.Split('\t');

            if (cells.Length < 6 || !TryKind(cells[3], out var kind))
            {
                continue;
            }

            var rank = int.Parse(cells[1], CultureInfo.InvariantCulture);
            var needed = int.Parse(cells[2], CultureInfo.InvariantCulture);
            int? value = cells[5].Length == 0 ? null : int.Parse(cells[5], CultureInfo.InvariantCulture);

            if (!rows.TryGetValue(cells[0], out var list))
            {
                list = [];
                rows[cells[0]] = list;
                powers.Add(cells[0]);
            }

            list.Add(new PowerplayReward(cells[0], rank, needed, kind, cells[4], value));
            merits.TryAdd(rank, needed);
        }

        foreach (var (power, list) in rows)
        {
            byPower[power] = list.OrderBy(r => r.Rank).ToList();
        }

        return new Table(powers, byPower, merits);
    }

    private static bool TryKind(string text, out PowerplayRewardKind kind)
    {
        kind = text switch
        {
            "decal" => PowerplayRewardKind.Decal,
            "care_package" => PowerplayRewardKind.CarePackage,
            "rebuy_own_territory" => PowerplayRewardKind.RebuyOwnTerritory,
            "rebuy_rival" => PowerplayRewardKind.RebuyRival,
            "perk" => PowerplayRewardKind.Perk,
            "module" => PowerplayRewardKind.Module,
            _ => (PowerplayRewardKind)(-1),
        };

        return (int)kind >= 0;
    }

    private sealed record Table(
        IReadOnlyList<string> Powers,
        IReadOnlyDictionary<string, IReadOnlyList<PowerplayReward>> ByPower,
        IReadOnlyDictionary<int, int> Merits);
}
