using System.Reflection;

namespace D47.Core.Knowledge;

/// <summary>
/// The shipped table of populated systems whose names no pattern recognises, generated by
/// <c>tools/gen-system-names.py</c>.
/// </summary>
public static class SystemNameTable
{
    private const string ResourceName = "D47.Core.SystemNames";

    private static readonly Lazy<(HashSet<string> Names, int LongestWordCount)> Loaded =
        new(Load, LazyThreadSafetyMode.ExecutionAndPublication);

    public static IReadOnlyCollection<string> Names => Loaded.Value.Names;

    /// <summary>The most words any name in the table has, counted as runs of letters and digits.</summary>
    public static int LongestWordCount => Loaded.Value.LongestWordCount;

    /// <summary>Whether the table holds this exact spelling.</summary>
    public static bool Contains(string name) => Loaded.Value.Names.Contains(name);

    private static (HashSet<string> Names, int LongestWordCount) Load()
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        using var stream = typeof(SystemNameTable).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName);

        if (stream is null)
        {
            return (names, 0);
        }

        using var reader = new StreamReader(stream);

        while (reader.ReadLine() is { } line)
        {
            if (line.Length > 0 && line[0] != '#')
            {
                names.Add(line);
            }
        }

        return (names, names.Count == 0 ? 0 : names.Max(name => SystemNameFinder.Words(name).Count));
    }
}
