using D47.Core.Knowledge;

namespace D47.Core.Adventures;

/// <summary>
/// What a beat needs before it can fire: its place, as an id, or the reason it cannot have one
/// (Phase 47, "Generated by d47 … needs one thing validation cannot give: a dry run").
/// </summary>
public sealed record Resolution(AdventureTrigger? Trigger, string? Refusal)
{
    public bool Succeeded => Trigger is not null;

    public static Resolution Of(AdventureTrigger trigger) => new(trigger, null);

    public static Resolution Refused(string reason) => new(null, reason);
}

/// <summary>
/// Turns the names a person or a model wrote into the ids the journal will match, through the
/// galaxy service (Phase 47).
/// <para>
/// One resolver for both authors. The editor's <em>Type a name</em> and the generator's dry run
/// ask the same questions — is this system real, is this station in it, is this body in it and can
/// it be landed on — and a second copy of the answers would be a second set of bugs. Every refusal
/// is a sentence naming the beat and the reason, which is what is printed under Begin.
/// </para>
/// <para>
/// Systems are resolved by the galaxy search's own id64, which is what the journal writes as
/// <c>SystemAddress</c>; stations by <c>market_id</c> and bodies by <c>body_id</c>, the same
/// numbers <c>Docked</c>, <c>Scan</c> and <c>Touchdown</c> carry. Names ride beside the ids in the
/// result, in the service's spelling rather than the author's.
/// </para>
/// </summary>
public sealed class AdventureResolver(IGalaxyService galaxy)
{
    private readonly Dictionary<string, (long Address, string Name)> _systems = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>A system by name: its address and the service's spelling, or null if it is not one.</summary>
    public async Task<(long Address, string Name)?> SystemAsync(string name, CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        var wanted = name.Trim();

        if (_systems.TryGetValue(wanted, out var cached))
        {
            return cached;
        }

        if (!GalaxyQuery.TryParse(
                wanted,
                new Dictionary<string, string>(StringComparer.Ordinal) { ["distance"] = "0-1" },
                size: 5,
                out var query,
                out _))
        {
            return null;
        }

        GalaxySearchResult result;

        try
        {
            result = await galaxy.SearchAsync(query, cancellationToken).ConfigureAwait(false);
        }
        catch (GalaxyUnavailableException ex) when (ex.Message.Contains("no record", StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        var hit = result.Systems.FirstOrDefault(system =>
            string.Equals(system.Name, wanted, StringComparison.OrdinalIgnoreCase) && system.SystemAddress is not null);

        if (hit?.SystemAddress is not { } address)
        {
            return null;
        }

        _systems[wanted] = (address, hit.Name);
        return (address, hit.Name);
    }

    /// <summary>
    /// A trigger from names. The kind and the names are what the author wrote; what comes back
    /// carries the ids, or says why it cannot.
    /// </summary>
    /// <param name="where">How to name the beat in a refusal — "Beat 3 (The Anchorage)".</param>
    /// <param name="needsLargePad">
    /// Whether a station has to have a large pad for anyone to dock there, read from the fleet by
    /// the caller. False for a Commander writing by hand, who knows their own ships.
    /// </param>
    public async Task<Resolution> ResolveAsync(
        TriggerKind kind,
        string? system,
        string? station,
        string? body,
        string where,
        bool needsLargePad,
        CancellationToken cancellationToken)
    {
        if (kind == TriggerKind.Rank)
        {
            return Resolution.Refused($"{where} is a rank beat, which needs no place.");
        }

        if (string.IsNullOrWhiteSpace(system))
        {
            return Resolution.Refused($"{where} names no system.");
        }

        try
        {
            var resolved = await SystemAsync(system, cancellationToken).ConfigureAwait(false);

            if (resolved is not { } found)
            {
                return Resolution.Refused($"{where} names a system, \"{system.Trim()}\", that the galaxy search does not know.");
            }

            switch (kind)
            {
                case TriggerKind.Arrive:
                    return Resolution.Of(new AdventureTrigger
                    {
                        Kind = TriggerKind.Arrive,
                        SystemAddress = found.Address,
                        System = found.Name,
                    });

                case TriggerKind.Dock:
                {
                    if (string.IsNullOrWhiteSpace(station))
                    {
                        return Resolution.Refused($"{where} docks nowhere: it names no station.");
                    }

                    var stations = await galaxy.FindStationsAsync(StationQuery.Within(found.Name), cancellationToken).ConfigureAwait(false);
                    var match = stations.Stations.FirstOrDefault(candidate =>
                        string.Equals(candidate.SystemName, found.Name, StringComparison.OrdinalIgnoreCase)
                        && string.Equals(candidate.Name, station.Trim(), StringComparison.OrdinalIgnoreCase));

                    if (match?.MarketId is null)
                    {
                        return Resolution.Refused($"{where} names a station, \"{station.Trim()}\", that is not in {found.Name}.");
                    }

                    if (needsLargePad && !match.HasLargePad)
                    {
                        return Resolution.Refused($"{where} docks at {match.Name}, which has no large pad, and the ship for this story needs one.");
                    }

                    return Resolution.Of(new AdventureTrigger
                    {
                        Kind = TriggerKind.Dock,
                        MarketId = match.MarketId,
                        SystemAddress = found.Address,
                        System = found.Name,
                        Station = match.Name,
                    });
                }

                case TriggerKind.Land:
                case TriggerKind.Scan:
                {
                    if (string.IsNullOrWhiteSpace(body))
                    {
                        return Resolution.Refused($"{where} names no body.");
                    }

                    var bodies = await galaxy.FindBodiesAsync(BodyQuery.Within(found.Name), cancellationToken).ConfigureAwait(false);
                    var match = MatchBody(bodies.Bodies, found.Name, body);

                    if (match?.BodyId is null)
                    {
                        return Resolution.Refused($"{where} names a body, \"{body.Trim()}\", that is not in {found.Name}.");
                    }

                    if (kind == TriggerKind.Land && !match.IsLandable)
                    {
                        return Resolution.Refused($"{where} lands on {match.Name}, which cannot be landed on.");
                    }

                    return Resolution.Of(new AdventureTrigger
                    {
                        Kind = kind,
                        SystemAddress = found.Address,
                        BodyId = match.BodyId,
                        System = found.Name,
                        Body = match.Name,
                    });
                }

                default:
                    return Resolution.Refused($"{where} names a trigger that is not one of the five.");
            }
        }
        catch (GalaxyUnavailableException ex)
        {
            return Resolution.Refused($"{where} could not be checked: {ex.Message}");
        }
    }

    /// <summary>Light years between two systems, or null where either is unknown.</summary>
    public Task<double?> DistanceAsync(string from, string to, CancellationToken cancellationToken) =>
        galaxy.DistanceAsync(from, to, cancellationToken);

    /// <summary>
    /// A body by its full name, or by the part after the system — a person writes "3 c" about as
    /// often as "Tavell's Reach 3 c", and both are the same body.
    /// </summary>
    internal static BodySummary? MatchBody(IReadOnlyList<BodySummary> bodies, string system, string wanted)
    {
        var trimmed = wanted.Trim();
        var inSystem = bodies.Where(body => string.Equals(body.SystemName, system, StringComparison.OrdinalIgnoreCase)).ToList();

        return inSystem.FirstOrDefault(body => string.Equals(body.Name, trimmed, StringComparison.OrdinalIgnoreCase))
               ?? inSystem.FirstOrDefault(body => string.Equals(body.Name, $"{system} {trimmed}", StringComparison.OrdinalIgnoreCase))
               ?? inSystem.FirstOrDefault(body => body.Name.EndsWith(" " + trimmed, StringComparison.OrdinalIgnoreCase));
    }
}
