using D47.Core.Journal;
using D47.Core.Knowledge;

namespace D47.Core.Adventures;

/// <summary>
/// What a beat needs before it can fire: its place, as an id, or the reason it cannot have one (Phase
/// 47, "Generated by d47 … needs one thing validation cannot give: a dry run").
/// </summary>
public sealed record Resolution(AdventureTrigger? Trigger, string? Refusal)
{
    public bool Succeeded => Trigger is not null;

    public static Resolution Of(AdventureTrigger trigger) => new(trigger, null);

    public static Resolution Refused(string reason) => new(null, reason);
}

/// <summary>
/// Turns the names a person or a model wrote into the ids the journal will match, through the galaxy
/// service (Phase 47).
/// </summary>
/// <param name="standings">The Commander's own readings of systems, weighed against the galaxy search's for war.</param>
public sealed class AdventureResolver(IGalaxyService galaxy, SystemStandings? standings = null)
{
    private readonly Dictionary<string, (long Address, string Name)> _systems = new(StringComparer.OrdinalIgnoreCase);

    private readonly Dictionary<string, string?> _governments = new(StringComparer.OrdinalIgnoreCase);

    private readonly Dictionary<string, (bool AtWar, DateTimeOffset? ReportedAt)> _wars = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>A station whose docks are offline, which a dock beat may not name.</summary>
    public long? ClosedMarketId { get; init; }

    /// <summary>A system by name: its address and the service's spelling, or null if it is not one.</summary>
    public async Task<(long Address, string Name)?> SystemAsync(string name, CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        var wanted = name.Trim();

        if (_systems.TryGetValue(wanted, out var cached))
        {
            return cached;
        }

        if (!GalaxyQuery.TryParse(
                wanted,
                new Dictionary<string, string>(StringComparer.Ordinal) { ["distance"] = "0-1" },
                size: 5,
                out var query,
                out _))
        {
            return null;
        }

        GalaxySearchResult result;

        try
        {
            result = await galaxy.SearchAsync(query, cancellationToken).ConfigureAwait(false);
        }
        catch (GalaxyUnavailableException ex) when (ex.Message.Contains("no record", StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        var hit = result.Systems.FirstOrDefault(system =>
            string.Equals(system.Name, wanted, StringComparison.OrdinalIgnoreCase) && system.SystemAddress is not null);

        if (hit?.SystemAddress is not { } address)
        {
            return null;
        }

        _systems[wanted] = (address, hit.Name);
        _governments[wanted] = hit.Government;
        _wars[wanted] = (hit.AtWar, hit.ReportedAt);
        return (address, hit.Name);
    }

    /// <summary>
    /// Whether a system has a war or civil war, active or pending, by whichever is newer: the Commander's
    /// own journal reading or the galaxy search's record. False where neither knows the system.
    /// </summary>
    public async Task<bool> AtWarAsync(string name, CancellationToken cancellationToken)
    {
        var reading = standings?.Latest(name.Trim());
        var record = (AtWar: false, ReportedAt: (DateTimeOffset?)null);
        var known = await SystemAsync(name, cancellationToken).ConfigureAwait(false) is not null
                    && _wars.TryGetValue(name.Trim(), out record);

        if (reading is not null && (!known || record.ReportedAt is not { } reported || reading.SeenAt >= reported))
        {
            return reading.Conflicts.Any(conflict =>
                conflict.WarType is "war" or "civilwar" && conflict.Status is "active" or "pending");
        }

        return known && record.AtWar;
    }

    private static bool IsSettlement(StationSummary station) =>
        string.Equals(station.Type, "Settlement", StringComparison.OrdinalIgnoreCase);

    /// <summary>Whether a dock beat may not name this station: a settlement in a system at war.</summary>
    public async Task<bool> ClosedByWarAsync(StationSummary station, CancellationToken cancellationToken) =>
        IsSettlement(station) && await AtWarAsync(station.SystemName, cancellationToken).ConfigureAwait(false);

    /// <summary>The government the galaxy search reports for a system, or null where it reports none or does not know the system.</summary>
    public async Task<string?> GovernmentAsync(string name, CancellationToken cancellationToken) =>
        await SystemAsync(name, cancellationToken).ConfigureAwait(false) is null
            ? null
            : _governments.GetValueOrDefault(name.Trim());

    private static string PadWord(PadSize size) => size.ToString().ToLowerInvariant();

    /// <summary>A trigger from names.</summary>
    /// <param name="where">How to name the beat in a refusal — "Beat 3 (The Anchorage)".</param>
    /// <param name="needsPad">The smallest pad a dock beat's station must have, or null for none.</param>
    public async Task<Resolution> ResolveAsync(
        TriggerKind kind,
        string? system,
        string? station,
        string? body,
        string where,
        PadSize? needsPad,
        CancellationToken cancellationToken)
    {
        if (kind == TriggerKind.Rank)
        {
            return Resolution.Refused($"{where} is a rank objective, which needs no place.");
        }

        if (AdventureTrigger.IsCountedKind(kind))
        {
            return Resolution.Refused($"{where} is a counted objective, which has no place of its own.");
        }

        if (string.IsNullOrWhiteSpace(system))
        {
            return Resolution.Refused($"{where} names no system.");
        }

        try
        {
            var resolved = await SystemAsync(system, cancellationToken).ConfigureAwait(false);

            if (resolved is not { } found)
            {
                return Resolution.Refused($"{where} names a system, \"{system.Trim()}\", that the galaxy search does not know.");
            }

            switch (kind)
            {
                case TriggerKind.Arrive:
                    return Resolution.Of(new AdventureTrigger
                    {
                        Kind = TriggerKind.Arrive,
                        SystemAddress = found.Address,
                        System = found.Name,
                    });

                case TriggerKind.Dock:
                {
                    if (string.IsNullOrWhiteSpace(station))
                    {
                        return Resolution.Refused($"{where} docks nowhere: it names no station.");
                    }

                    var stations = await galaxy.FindStationsAsync(StationQuery.Within(found.Name), cancellationToken).ConfigureAwait(false);
                    var match = stations.Stations.FirstOrDefault(candidate =>
                        string.Equals(candidate.SystemName, found.Name, StringComparison.OrdinalIgnoreCase)
                        && string.Equals(candidate.Name, station.Trim(), StringComparison.OrdinalIgnoreCase));

                    if (match?.MarketId is null)
                    {
                        return Resolution.Refused($"{where} names a station, \"{station.Trim()}\", that is not in {found.Name}.");
                    }

                    if (match.MarketId == ClosedMarketId)
                    {
                        return Resolution.Refused($"{where} docks at {match.Name}, whose docks are offline.");
                    }

                    if (needsPad is { } pad && !match.Admits(pad))
                    {
                        return Resolution.Refused($"{where} docks at {match.Name}, which has no {PadWord(pad)} pad or larger, and the ship for this story needs one.");
                    }

                    if (IsSettlement(match) && await AtWarAsync(found.Name, cancellationToken).ConfigureAwait(false))
                    {
                        return Resolution.Refused($"{where} docks at {match.Name}, a settlement in {found.Name}, which is at war; its docks may be closed for fighting on the ground.");
                    }

                    return Resolution.Of(new AdventureTrigger
                    {
                        Kind = TriggerKind.Dock,
                        MarketId = match.MarketId,
                        SystemAddress = found.Address,
                        System = found.Name,
                        Station = match.Name,
                    });
                }

                case TriggerKind.Land:
                case TriggerKind.Scan:
                {
                    if (string.IsNullOrWhiteSpace(body))
                    {
                        return Resolution.Refused($"{where} names no body.");
                    }

                    var bodies = await galaxy.FindBodiesAsync(BodyQuery.Within(found.Name), cancellationToken).ConfigureAwait(false);
                    var match = MatchBody(bodies.Bodies, found.Name, body);

                    if (match?.BodyId is null)
                    {
                        return Resolution.Refused($"{where} names a body, \"{body.Trim()}\", that is not in {found.Name}.");
                    }

                    if (kind == TriggerKind.Land && !match.IsLandable)
                    {
                        return Resolution.Refused($"{where} lands on {match.Name}, which cannot be landed on.");
                    }

                    return Resolution.Of(new AdventureTrigger
                    {
                        Kind = kind,
                        SystemAddress = found.Address,
                        BodyId = match.BodyId,
                        System = found.Name,
                        Body = match.Name,
                    });
                }

                default:
                    return Resolution.Refused($"{where} names a trigger that has no place to resolve.");
            }
        }
        catch (GalaxyUnavailableException ex)
        {
            return Resolution.Refused($"{where} could not be checked: {ex.Message}");
        }
    }

    /// <summary>Light years between two systems, or null where either is unknown.</summary>
    public Task<double?> DistanceAsync(string from, string to, CancellationToken cancellationToken) =>
        galaxy.DistanceAsync(from, to, cancellationToken);

    /// <summary>
    /// A body by its full name, or by the part after the system — a person writes "3 c" about as often
    /// as "Tavell's Reach 3 c", and both are the same body.
    /// </summary>
    internal static BodySummary? MatchBody(IReadOnlyList<BodySummary> bodies, string system, string wanted)
    {
        var trimmed = wanted.Trim();
        var inSystem = bodies.Where(body => string.Equals(body.SystemName, system, StringComparison.OrdinalIgnoreCase)).ToList();

        return inSystem.FirstOrDefault(body => string.Equals(body.Name, trimmed, StringComparison.OrdinalIgnoreCase))
               ?? inSystem.FirstOrDefault(body => string.Equals(body.Name, $"{system} {trimmed}", StringComparison.OrdinalIgnoreCase))
               ?? inSystem.FirstOrDefault(body => body.Name.EndsWith(" " + trimmed, StringComparison.OrdinalIgnoreCase));
    }
}
