<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\D47.Core\D47.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="D47.App.Tests" />
    <InternalsVisibleTo Include="D47.Llm.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.40.0" />
  </ItemGroup>

</Project>
