#!/usr/bin/env python3
"""Regenerate d47's table of hand-named populated star systems.

Not part of the build. Its output is committed as `src/D47.Core/Knowledge/SystemNames.tsv` and
shipped as an embedded resource; the app never runs this and never reaches the network for it.
Run it when Frontier names or populates systems:

    python tools/gen-system-names.py

Downloads EDSM's nightly dump of populated systems (about 500 MB compressed) to a temporary file,
keeps each system's name and nothing else, and leaves out every name `SystemNameFinder` already
recognises by pattern. The two patterns below are ports of the ones in
`src/D47.Core/Knowledge/SystemNameFinder.cs` and change with them; a Core test fails when a row
matches either.
"""

from __future__ import annotations

import gzip
import json
import re
import shutil
import sys
import tempfile
import urllib.request
from email.utils import parsedate_to_datetime
from pathlib import Path

SOURCE = "https://www.edsm.net/dump/systemsPopulated.json.gz"

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "D47.Core" / "Knowledge" / "SystemNames.tsv"

SECTOR_WORD = r"[A-Z0-9(][A-Za-z0-9'.()]*"
SECTOR = (
    rf"(?:[A-Z][A-Za-z0-9'.()]*(?: {SECTOR_WORD}){{0,3}} (?:Sector|Region)"
    r"|ICZ|[A-Z][a-z]+(?: [A-Z][a-z]+)?)"
)
BOXEL = r"[A-Z]{2}-[A-Z] [a-h](?:\d+-)?\d+"
PREFIX = (
    "2MASS|Groombridge|Lalande|Luyten|Struve|Gliese|Kruger|LAWD|NLTT|SDSS|StKM|Ross|WISE|Wolf"
    "|CPD|HIP|LFT|LHS|LTT|BD|CD|GJ|HD|HR|LP|G"
)
GROUP = r"\d(?:[\d.+\-]*\d)?"
CATALOGUE = rf"(?:{PREFIX})(?: [+\-]?|[+\-]){GROUP}(?: {GROUP})?"

PROCEDURAL = re.compile(rf"{SECTOR} {BOXEL}")
CATALOGUED = re.compile(CATALOGUE)


def download(target: Path) -> str:
    """Fetches the dump and returns the date the server says it was written."""
    request = urllib.request.Request(SOURCE, headers={"User-Agent": "d47-gen-system-names"})

    with urllib.request.urlopen(request, timeout=120) as response, target.open("wb") as handle:
        modified = response.headers.get("Last-Modified")
        shutil.copyfileobj(response, handle, length=1 << 20)

    return parsedate_to_datetime(modified).date().isoformat() if modified else "an unstated date"


def names(dump: Path) -> set[str]:
    """Every name the patterns miss. The dump is a JSON array with one system per line."""
    kept: set[str] = set()
    read = 0

    with gzip.open(dump, "rt", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip().rstrip(",")

            if not line.startswith("{"):
                continue

            name = str(json.loads(line)["name"]).strip()
            read += 1

            if not name or PROCEDURAL.fullmatch(name) or CATALOGUED.fullmatch(name):
                continue

            assert "\t" not in name and "\n" not in name, name
            kept.add(name)

    print(f"Read {read} systems, kept {len(kept)}", file=sys.stderr)
    assert read > 10_000, "the dump is smaller than any real one"
    return kept


def main() -> int:
    with tempfile.TemporaryDirectory() as directory:
        dump = Path(directory) / "systemsPopulated.json.gz"
        dated = download(dump)
        rows = sorted(names(dump))

    header = [
        "# Generated by tools/gen-system-names.py. Do not edit by hand — rerun the tool.",
        f"# Source: {SOURCE}, dated {dated}.",
        "# System names only, which are Frontier's game data; see NOTICE. Names the procedural and",
        "# catalogue patterns in SystemNameFinder recognise are left out.",
    ]

    OUTPUT.write_text("\n".join(header + rows) + "\n", encoding="utf-8", newline="\n")

    print(f"Wrote {len(rows)} rows to {OUTPUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
