#!/usr/bin/env python3
"""Regenerate d47's table of landing pad positions in a ring station.

Not part of the build. Its output is committed as `src/D47.Core/Knowledge/LandingPads.tsv`
and shipped as an embedded resource; the app never runs this and never reaches the network
for it. Run it by hand if the source table changes:

    python tools/gen-landing-pads.py

The source is the `pads` array in rdnt/ed-landing-pads' index.html, read at a pinned
revision. Each entry is `pad,segment,depth,size`: segment 1 to 12 around the ring, 30 degrees
apart, segment 1 nearest beneath a ship entering with the green lights on its right; depth 0
to 4 from the entrance; size 1 small, 2 medium, 3 large. The layout is shared by Coriolis,
Orbis, Ocellus and asteroid bases.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

REPOSITORY = "https://github.com/rdnt/ed-landing-pads"
REVISION = "ca9b381cf8a7348ee7e93d603f1149a73109b6dd"
SOURCE = f"https://raw.githubusercontent.com/rdnt/ed-landing-pads/{REVISION}/index.html"

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "D47.Core" / "Knowledge" / "LandingPads.tsv"

PADS = 45


def main() -> None:
    request = urllib.request.Request(SOURCE, headers={"User-Agent": "d47-gen-landing-pads"})
    with urllib.request.urlopen(request, timeout=60) as response:
        html = response.read().decode("utf-8")

    array = re.search(r"var pads = \[(.*?)\]", html, re.DOTALL)
    if array is None:
        raise SystemExit("No pads array in the source page.")

    rows = []
    for pad, segment, depth, size in re.findall(r'"(\d+),(\d+),(\d+),(\d+)"', array.group(1)):
        row = int(pad), int(segment), int(depth), int(size)
        if not (1 <= row[1] <= 12 and 0 <= row[2] <= 4 and 1 <= row[3] <= 3):
            raise SystemExit(f"Out of range: {row}")
        rows.append(row)

    if sorted(r[0] for r in rows) != list(range(1, PADS + 1)):
        raise SystemExit(f"Expected pads 1 to {PADS}, read {len(rows)}.")

    lines = [
        "# Generated by tools/gen-landing-pads.py. Do not edit by hand — rerun the tool.",
        f"# Source: {REPOSITORY} at {REVISION}, index.html.",
        "# (c) 2018 Tasos Papalyras, MIT; see NOTICE.",
        "# pad\tsegment\tdepth\tsize",
    ]
    lines += [f"{p}\t{s}\t{d}\t{z}" for p, s, d, z in sorted(rows)]

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {len(rows)} pads to {OUTPUT}")


if __name__ == "__main__":
    main()
