#!/usr/bin/env python3
"""Regenerate d47's galactic region boundary table.

Not part of the build. Its output is committed as
`src/D47.Core/Knowledge/Regions.tsv` and shipped as an embedded resource; the app never
runs this and never reaches the network for it. Run it when the region boundaries change,
which happens on the pinned commit below rather than on every run:

    python tools/gen-regions.py

What it answers
----------------
`GalacticRegions.Find` places a `StarPosition` in one of the 42 codex regions Frontier's galaxy
map names — "Inner Orion Spur", "Inner Scutum-Centaurus Arm" and so on — which the journal does
not state and nothing already in d47 derives. `klightspeed/EliteDangerousRegionMap` (MIT) carries
both the boundary table and the lookup it is read with: `RegionMapData.json` grids the galaxy into
rows along z, each row a run-length list of (span, region id) pairs along x, and `RegionMap.cs`'s
`FindRegion` walks one row of it. `GalacticRegions.Find` in
`src/D47.Core/Knowledge/GalacticRegions.cs` is a straight port of that function; this script ports
the data it reads, from JSON into the tab-separated table the rest of d47's Knowledge tables use.

Pinned by commit rather than by branch: the row format is undocumented outside `RegionMap.cs`
itself, so a restructure upstream would change what this script's column layout means rather than
break it. Bump deliberately, and re-check `FindRegion` for a matching change before trusting a new
pin.
"""

import json
import urllib.request
from pathlib import Path

COMMIT = "6c1191a58e1e593966f44f16235ab39d1ad24d84"

DATA_URL = (
    f"https://raw.githubusercontent.com/klightspeed/EliteDangerousRegionMap/{COMMIT}/RegionMapData.json"
)

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "D47.Core" / "Knowledge" / "Regions.tsv"


def main() -> int:
    with urllib.request.urlopen(DATA_URL, timeout=30) as response:
        data = json.loads(response.read().decode("utf-8"))

    regions: list[str | None] = data["regions"]
    rows: list[list[list[int]]] = data["regionmap"]

    assert regions[0] is None, "row 0 of the region table is expected to be the unnamed 'outside the map' id"
    assert len(regions) == 43, f"expected 42 named regions plus the unnamed id 0, found {len(regions) - 1}"

    lines = [
        "# Generated by tools/gen-regions.py. Do not edit by hand — rerun the tool.",
        f"# Source: klightspeed/EliteDangerousRegionMap RegionMapData.json (MIT) at commit {COMMIT[:12]}.",
        "# N rows name a region by id; M rows are one row of the boxel grid along z (pz), as a",
        "# comma-separated list of span:id run-length pairs along x — see GalacticRegions.Find, which",
        "# ports RegionMap.cs's FindRegion over this same encoding. Region names are Frontier's own",
        "# codex region names; see NOTICE.",
        f"# Regions: {len(regions) - 1}. Map rows: {len(rows)}.",
    ]

    for region_id, name in enumerate(regions):
        if name is not None:
            lines.append(f"N\t{region_id}\t{name}")

    for pz, row in enumerate(rows):
        runs = ",".join(f"{span}:{region_id}" for span, region_id in row)
        lines.append(f"M\t{pz}\t{runs}")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    print(f"Wrote {len(regions) - 1} regions and {len(rows)} map rows to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
