#!/usr/bin/env python3
"""Regenerate d47's material grade table.

This is *not* part of the build. Its output is committed as
`src/D47.Core/Journal/MaterialGrades.g.cs`, and the app never runs it or reaches the
network for it — it exists so the table is *derived* rather than hand-authored. Run it
only when Frontier adds or reclassifies a material:

    python tools/gen-material-grades.py

Why this table exists at all
----------------------------
Phase 8's material milestones need a per-material capacity, and Elite reports capacity
nowhere: not in a journal event, not in Status.json, not in the `Materials` snapshot.
The game simply stops accepting more. Capacity is set by the material's *grade*, and the
grade is not in the journal either.

So the choice was between shipping a table and dropping the feature. A hand-written table
of ~130 grades would be exactly the kind of confidently-invented game data the guardrails
exist to prevent — a wrong entry surfaces as a milestone announced at the wrong number,
which is indistinguishable from the feature working. A *derived* table is a different
thing: it is checkable, refreshable, and traceable to something that is not d47's memory.

Source
------
`EDCD/FDevIDs` `material.csv` — the canonical community-maintained id list, the same data
Coriolis and EDEngineer are built on. Its `rarity` column is the grade (1-5), `type` is
the category, and `symbol` is the lower-case name the `Materials` journal event uses.

The grade-to-capacity mapping is a fixed game rule rather than per-material data:
300/250/200/150/100 for grades 1 through 5. It lives in `MaterialGrades.CapacityOfGrade`
next to the generated table, not in it, because it is five numbers that do not change when
Frontier adds a material.
"""

import csv
import io
import urllib.request
from pathlib import Path

# The materials FDevIDs does not name, from the one place gen-materials.py reads them too
# (<https://github.com/dseelinger/d47/issues/127>). Both tables are built from the same
# authority and asserted against each other, so a curated row in one and not the other is two
# shipped tables disagreeing.
from curated_materials import CURATED

SOURCE = "https://raw.githubusercontent.com/EDCD/FDevIDs/master/material.csv"

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "D47.Core" / "Journal" / "MaterialGrades.g.cs"

HEADER = '''// <auto-generated>
//   Generated by tools/gen-material-grades.py from EDCD/FDevIDs material.csv.
//   Do not edit by hand — rerun the tool instead. See that file for why this table is
//   derived rather than written, and why d47 needs it at all.
//
//   Source: {source}
//   Materials: {count}
// </auto-generated>

namespace D47.Core.Journal;

public static partial class MaterialGrades
{{
    /// <summary>
    /// Journal name to grade, derived from the canonical id list. The key is the lower-case
    /// <c>Name</c> the <c>Materials</c> event writes, which is what
    /// <see cref="MaterialsInventory"/> keys its holdings by.
    /// </summary>
    private static readonly Dictionary<string, int> ByName = new(StringComparer.OrdinalIgnoreCase)
    {{
'''

FOOTER = '''    };
}
'''


def main() -> None:
    with urllib.request.urlopen(SOURCE) as response:
        text = response.read().decode("utf-8-sig")

    rows = list(csv.DictReader(io.StringIO(text)))

    entries = []
    for row in rows:
        symbol = (row.get("symbol") or "").strip()
        rarity = (row.get("rarity") or "").strip()
        category = (row.get("type") or "").strip()

        if not symbol or not rarity:
            # Fail loud rather than dropping a material silently: a missing entry is a
            # milestone that never fires, which looks exactly like the feature being off.
            raise SystemExit(f"material.csv row has no symbol or rarity: {row}")

        grade = int(rarity)
        if grade < 1 or grade > 5:
            raise SystemExit(f"{symbol} has grade {grade}, which is outside 1-5")

        if category not in ("Raw", "Manufactured", "Encoded"):
            raise SystemExit(f"{symbol} has unexpected category {category!r}")

        entries.append((symbol.lower(), grade, category))

    named = {symbol for symbol, _grade, _category in entries}

    for symbol, _name, category, grade in CURATED:
        if symbol in named:
            # FDevIDs has caught up. Its row wins and the curated one is reported as droppable
            # rather than silently shadowing the authority.
            print(f"FDevIDs now names {symbol}, so drop it from tools/curated_materials.py")
            continue

        entries.append((symbol, grade, category))

    entries.sort()

    body = "".join(
        f'        ["{symbol}"] = {grade}, // {category} grade {grade}\n'
        for symbol, grade, category in entries
    )

    OUTPUT.write_text(
        HEADER.format(source=SOURCE, count=len(entries)) + body + FOOTER,
        encoding="utf-8",
        newline="\n",
    )

    by_grade = {}
    for _, grade, _ in entries:
        by_grade[grade] = by_grade.get(grade, 0) + 1

    print(f"Wrote {len(entries)} materials to {OUTPUT}")
    print("Per grade: " + ", ".join(f"G{g}={by_grade[g]}" for g in sorted(by_grade)))


if __name__ == "__main__":
    main()
