namespace D47.Core.Audio;

public sealed class WavFormatException(string message) : Exception(message);

/// <summary>
/// Just enough RIFF to read the shipped cues: 16-bit PCM, any rate, any channel count.
/// <para>
/// Deliberately strict. These files are generated by `tools/gen-cues.py` and committed, so
/// anything this reader cannot parse is a mistake in the generator or a corrupted commit,
/// and neither is worth guessing around. A cue that silently loads as noise is worse than
/// one that refuses to load.
/// </para>
/// </summary>
public static class WavReader
{
    public static AudioClip Read(string path)
    {
        using var stream = File.OpenRead(path);
        return Read(stream, Path.GetFileNameWithoutExtension(path));
    }

    public static AudioClip Read(Stream stream, string name)
    {
        using var reader = new BinaryReader(stream, System.Text.Encoding.ASCII, leaveOpen: true);

        if (new string(reader.ReadChars(4)) != "RIFF")
        {
            throw new WavFormatException($"{name} is not a RIFF file.");
        }

        reader.ReadUInt32(); // Total size, which we do not need and will not trust.

        if (new string(reader.ReadChars(4)) != "WAVE")
        {
            throw new WavFormatException($"{name} is RIFF but not WAVE.");
        }

        AudioFormat? format = null;

        // Chunk order is not guaranteed by the spec, and real encoders put LIST and fact
        // chunks between fmt and data. Walk rather than assume.
        while (stream.Position < stream.Length - 8)
        {
            var chunkId = new string(reader.ReadChars(4));
            var chunkSize = reader.ReadUInt32();

            switch (chunkId)
            {
                case "fmt ":
                {
                    var encoding = reader.ReadUInt16();
                    var channels = reader.ReadUInt16();
                    var sampleRate = (int)reader.ReadUInt32();
                    reader.ReadUInt32(); // Byte rate, derivable.
                    reader.ReadUInt16(); // Block align, derivable.
                    var bitsPerSample = reader.ReadUInt16();

                    if (encoding != 1)
                    {
                        throw new WavFormatException(
                            $"{name} is encoding {encoding}; only uncompressed PCM is supported.");
                    }

                    if (bitsPerSample != 16)
                    {
                        throw new WavFormatException(
                            $"{name} is {bitsPerSample}-bit; only 16-bit is supported.");
                    }

                    format = new AudioFormat(sampleRate, channels);

                    // fmt is 16 bytes for PCM but may carry an extension.
                    Skip(stream, (int)chunkSize - 16);
                    break;
                }

                case "data":
                {
                    if (format is null)
                    {
                        throw new WavFormatException($"{name} has a data chunk before its fmt chunk.");
                    }

                    return new AudioClip(name, reader.ReadBytes((int)chunkSize), format);
                }

                default:
                    Skip(stream, (int)chunkSize);
                    break;
            }

            // Chunks are word-aligned; an odd size carries a pad byte that is not counted.
            if (chunkSize % 2 == 1)
            {
                Skip(stream, 1);
            }
        }

        throw new WavFormatException($"{name} has no data chunk.");
    }

    private static void Skip(Stream stream, int count)
    {
        if (count > 0)
        {
            stream.Seek(count, SeekOrigin.Current);
        }
    }
}
