using System.Collections.Frozen;

namespace D47.Core.Journal;

/// <summary>The journal events d47 acts on — one list, bound to the code by a gate (#270).</summary>
public static class HandledEvents
{
    /// <summary>
    /// Events something reacts to: folded into game state, spoken about, planned from, mined for a
    /// goal, written into the logbook, or used to bound a log range.
    /// </summary>
    public static readonly FrozenSet<string> ActedOn = FrozenSet.ToFrozenSet<string>(
    [
        "ApproachBody",
        "ApproachSettlement",
        "AsteroidCracked",
        "BackpackChange",
        "Bounty",
        "BuySuit",
        "BuyWeapon",
        "Cargo",
        "CargoDepot",
        "CargoTransfer",
        "CarrierBankTransfer",
        "CarrierBuy",
        "CarrierCrewServices",
        "CarrierDepositFuel",
        "CarrierJump",
        "CarrierJumpCancelled",
        "CarrierJumpRequest",
        "CarrierLocation",
        "CarrierModulePack",
        "CarrierShipPack",
        "CarrierStats",
        "CarrierTradeOrder",
        "CodexEntry",
        "CollectCargo",
        "CollectItems",
        "ColonisationConstructionDepot",
        "ColonisationContribution",
        "Commander",
        "CommitCrime",
        "CommunityGoal",
        "CommunityGoalDiscard",
        "CommunityGoalJoin",
        "CommunityGoalReward",
        "CreateSuitLoadout",
        "CrewAssign",
        "CrewFire",
        "CrewHire",
        "DataScanned",
        "Died",
        "DisbandedSquadron",
        "Disembark",
        "DockFighter",
        "DockSRV",
        "Docked",
        "DockingCancelled",
        "DockingDenied",
        "DockingGranted",
        "DockingRequested",
        "DockingTimeout",
        "EjectCargo",
        "Embark",
        "EngineerContribution",
        "EngineerCraft",
        "EngineerProgress",
        "FSDJump",
        "FSDTarget",
        "FSSBodySignals",
        "FSSDiscoveryScan",
        "FSSSignalDiscovered",
        "FactionKillBond",
        "FighterDestroyed",
        "FighterRebuilt",
        "FuelScoop",
        "HeatDamage",
        "HullDamage",
        "Interdicted",
        "Interdiction",
        "JoinACrew",
        "JoinedSquadron",
        "KickedFromSquadron",
        "LaunchDrone",
        "LaunchFighter",
        "LaunchSRV",
        "LeaveBody",
        "LeftSquadron",
        "Liftoff",
        "LoadGame",
        "Loadout",
        "LoadoutEquipModule",
        "LoadoutRemoveModule",
        "Location",
        "Market",
        "MarketBuy",
        "MarketSell",
        "MaterialCollected",
        "MaterialDiscarded",
        "MaterialTrade",
        "Materials",
        "MiningRefined",
        "MissionAbandoned",
        "MissionAccepted",
        "MissionCompleted",
        "MissionFailed",
        "MissionRedirected",
        "Missions",
        "ModuleBuy",
        "ModuleSell",
        "ModuleSellRemote",
        "MultiSellExplorationData",
        "Music",
        "NavRoute",
        "NewCommander",
        "NpcCrewRank",
        "PayBounties",
        "PayFines",
        "Powerplay",
        "PowerplayDefect",
        "PowerplayJoin",
        "PowerplayLeave",
        "PowerplayMerits",
        "PowerplayRank",
        "Progress",
        "Promotion",
        "ProspectedAsteroid",
        "Rank",
        "ReceiveText",
        "RedeemVoucher",
        "RefuelAll",
        "Repair",
        "RepairAll",
        "Reputation",
        "Resurrect",
        "SAAScanComplete",
        "SAASignalsFound",
        "SRVDestroyed",
        "Scan",
        "ScanOrganic",
        "ScientificResearch",
        "SearchAndRescue",
        "SellExplorationData",
        "SellMicroResources",
        "SellOrganicData",
        "SellSuit",
        "SellWeapon",
        "SetUserShipName",
        "ShieldState",
        "ShipTargeted",
        "ShipyardBuy",
        "ShipyardNew",
        "ShipyardSell",
        "ShipyardSwap",
        "Shutdown",
        "SquadronCreated",
        "SquadronStartup",
        "StartJump",
        "Statistics",
        "StoredModules",
        "StoredShips",
        "SuitLoadout",
        "SupercruiseDestinationDrop",
        "SupercruiseEntry",
        "SupercruiseExit",
        "SwitchSuitLoadout",
        "Synthesis",
        "TechnologyBroker",
        "Touchdown",
        "USSDrop",
        "UnderAttack",
        "Undocked",
        "UpgradeSuit",
        "UpgradeWeapon",
        "WingAdd",
        "WingJoin",
    ], StringComparer.Ordinal);

    /// <summary>
    /// Events Frontier writes that d47 deliberately answers neither block for: <c>Backpack</c> is the
    /// on-foot inventory, read from <c>Backpack.json</c> instead;
    /// <c>CancelDropship</c> is a cancelled on-foot dropship booking, carrying a refund and nothing
    /// d47 tracks; <c>FCMaterials</c> is the carrier's materials market, tabled to the carrier
    /// reminder work (#24).
    /// </summary>
    public static readonly FrozenSet<string> Intentional = FrozenSet.ToFrozenSet<string>(
    [
        "Backpack",
        "CancelDropship",
        "FCMaterials",
    ], StringComparer.Ordinal);

    /// <summary>
    /// Events only the Journal File reading knows: it has a sentence for each, or hides it as noise,
    /// and nothing else in d47 reacts to it.
    /// </summary>
    public static readonly FrozenSet<string> NarratedOnly = FrozenSet.ToFrozenSet<string>(
    [
        "AfmuRepairs",
        "AppliedToSquadron",
        "BookDropship",
        "BookTaxi",
        "BuyAmmo",
        "BuyDrones",
        "BuyExplorationData",
        "BuyMicroResources",
        "CancelTaxi",
        "CarrierDecommission",
        "CarrierDockingPermission",
        "CarrierFinance",
        "CarrierNameChange",
        "ChangeCrewRole",
        "ColonisationBeaconDeployed",
        "ColonisationSystemClaim",
        "CompleteConstruction",
        "CrimeVictim",
        "DatalinkScan",
        "DatalinkVoucher",
        "DeleteSuitLoadout",
        "DeliverPowerMicroResources",
        "DiscoveryScan",
        "DropItems",
        "DropshipDeploy",
        "EscapeInterdiction",
        "FSSAllBodiesFound",
        "FetchRemoteModule",
        "Fileheader",
        "Friends",
        "GameModeChange",
        "HeatWarning",
        "JetConeBoost",
        "MaterialDiscovered",
        "ModuleBuyAndStore",
        "ModuleInfo",
        "ModuleRetrieve",
        "ModuleStore",
        "NavBeaconScan",
        "NavRouteClear",
        "NpcCrewPaidWage",
        "Outfitting",
        "PowerplayCollect",
        "PowerplayDeliver",
        "QuitACrew",
        "RebootRepair",
        "RenameSuitLoadout",
        "RepairDrone",
        "ReservoirReplenished",
        "RestockVehicle",
        "Resupply",
        "ScanBaryCentre",
        "Scanned",
        "Screenshot",
        "SellDrones",
        "SendText",
        "SharedBookmarkToSquadron",
        "ShipLocker",
        "ShipRedeemed",
        "Shipyard",
        "ShipyardBankDeposit",
        "ShipyardRedeem",
        "ShipyardTransfer",
        "SquadronApplicationApproved",
        "SquadronPromotion",
        "TradeMicroResources",
        "UseConsumable",
        "WingInvite",
        "WingLeave",
    ], StringComparer.Ordinal);

    /// <summary>All three blocks: whether d47 knows the event at all.</summary>
    public static readonly FrozenSet<string> All =
        ActedOn.Concat(NarratedOnly).Concat(Intentional).ToFrozenSet(StringComparer.Ordinal);

    /// <summary>
    /// Of the event names seen — in a corpus, a session, a Frontier update's notes — the ones nothing
    /// in d47 matches.
    /// </summary>
    public static IReadOnlyList<string> Unhandled(IEnumerable<string> seen) =>
        [.. seen.Where(kind => !All.Contains(kind)).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal)];
}
