// <auto-generated>
//   Generated by tools/gen-material-grades.py from EDCD/FDevIDs material.csv.
//   Do not edit by hand — rerun the tool instead. See that file for why this table is
//   derived rather than written, and why d47 needs it at all.
//
//   Source: https://raw.githubusercontent.com/EDCD/FDevIDs/master/material.csv
//   Materials: 140
// </auto-generated>

namespace D47.Core.Journal;

public static partial class MaterialGrades
{
    /// <summary>
    /// Journal name to grade, derived from the canonical id list. The key is the lower-case
    /// <c>Name</c> the <c>Materials</c> event writes, which is what
    /// <see cref="MaterialsInventory"/> keys its holdings by.
    /// </summary>
    private static readonly Dictionary<string, int> ByName = new(StringComparer.OrdinalIgnoreCase)
    {
        ["adaptiveencryptors"] = 5, // Encoded grade 5
        ["ancientbiologicaldata"] = 4, // Encoded grade 4
        ["ancientculturaldata"] = 4, // Encoded grade 4
        ["ancienthistoricaldata"] = 4, // Encoded grade 4
        ["ancientlanguagedata"] = 4, // Encoded grade 4
        ["ancienttechnologicaldata"] = 4, // Encoded grade 4
        ["antimony"] = 4, // Raw grade 4
        ["archivedemissiondata"] = 2, // Encoded grade 2
        ["arsenic"] = 2, // Raw grade 2
        ["basicconductors"] = 1, // Manufactured grade 1
        ["biotechconductors"] = 5, // Manufactured grade 5
        ["boron"] = 3, // Raw grade 3
        ["bulkscandata"] = 1, // Encoded grade 1
        ["cadmium"] = 3, // Raw grade 3
        ["carbon"] = 1, // Raw grade 1
        ["chemicaldistillery"] = 3, // Manufactured grade 3
        ["chemicalmanipulators"] = 4, // Manufactured grade 4
        ["chemicalprocessors"] = 2, // Manufactured grade 2
        ["chemicalstorageunits"] = 1, // Manufactured grade 1
        ["chromium"] = 2, // Raw grade 2
        ["classifiedscandata"] = 5, // Encoded grade 5
        ["compactcomposites"] = 1, // Manufactured grade 1
        ["compactemissionsdata"] = 5, // Encoded grade 5
        ["compoundshielding"] = 4, // Manufactured grade 4
        ["conductiveceramics"] = 3, // Manufactured grade 3
        ["conductivecomponents"] = 2, // Manufactured grade 2
        ["conductivepolymers"] = 4, // Manufactured grade 4
        ["configurablecomponents"] = 4, // Manufactured grade 4
        ["consumerfirmware"] = 2, // Encoded grade 2
        ["crystalshards"] = 1, // Manufactured grade 1
        ["dataminedwake"] = 5, // Encoded grade 5
        ["decodedemissiondata"] = 4, // Encoded grade 4
        ["disruptedwakeechoes"] = 1, // Encoded grade 1
        ["electrochemicalarrays"] = 3, // Manufactured grade 3
        ["embeddedfirmware"] = 5, // Encoded grade 5
        ["emissiondata"] = 3, // Encoded grade 3
        ["encodedscandata"] = 4, // Encoded grade 4
        ["encryptedfiles"] = 1, // Encoded grade 1
        ["encryptionarchives"] = 4, // Encoded grade 4
        ["encryptioncodes"] = 2, // Encoded grade 2
        ["exquisitefocuscrystals"] = 5, // Manufactured grade 5
        ["fedcorecomposites"] = 5, // Manufactured grade 5
        ["fedproprietarycomposites"] = 4, // Manufactured grade 4
        ["filamentcomposites"] = 2, // Manufactured grade 2
        ["focuscrystals"] = 3, // Manufactured grade 3
        ["fsdtelemetry"] = 2, // Encoded grade 2
        ["galvanisingalloys"] = 2, // Manufactured grade 2
        ["germanium"] = 2, // Raw grade 2
        ["gridresistors"] = 1, // Manufactured grade 1
        ["guardian_moduleblueprint"] = 4, // Encoded grade 4
        ["guardian_powercell"] = 1, // Manufactured grade 1
        ["guardian_powerconduit"] = 2, // Manufactured grade 2
        ["guardian_sentinel_weaponparts"] = 3, // Manufactured grade 3
        ["guardian_sentinel_wreckagecomponents"] = 1, // Manufactured grade 1
        ["guardian_techcomponent"] = 3, // Manufactured grade 3
        ["guardian_vesselblueprint"] = 5, // Encoded grade 5
        ["guardian_weaponblueprint"] = 4, // Encoded grade 4
        ["heatconductionwiring"] = 1, // Manufactured grade 1
        ["heatdispersionplate"] = 2, // Manufactured grade 2
        ["heatexchangers"] = 3, // Manufactured grade 3
        ["heatresistantceramics"] = 2, // Manufactured grade 2
        ["heatvanes"] = 4, // Manufactured grade 4
        ["highdensitycomposites"] = 3, // Manufactured grade 3
        ["hybridcapacitors"] = 2, // Manufactured grade 2
        ["hyperspacetrajectories"] = 4, // Encoded grade 4
        ["imperialshielding"] = 5, // Manufactured grade 5
        ["improvisedcomponents"] = 5, // Manufactured grade 5
        ["industrialfirmware"] = 3, // Encoded grade 3
        ["iron"] = 1, // Raw grade 1
        ["lead"] = 1, // Raw grade 1
        ["legacyfirmware"] = 1, // Encoded grade 1
        ["manganese"] = 2, // Raw grade 2
        ["mechanicalcomponents"] = 3, // Manufactured grade 3
        ["mechanicalequipment"] = 2, // Manufactured grade 2
        ["mechanicalscrap"] = 1, // Manufactured grade 1
        ["mercury"] = 3, // Raw grade 3
        ["militarygradealloys"] = 5, // Manufactured grade 5
        ["militarysupercapacitors"] = 5, // Manufactured grade 5
        ["molybdenum"] = 3, // Raw grade 3
        ["nickel"] = 1, // Raw grade 1
        ["niobium"] = 3, // Raw grade 3
        ["pharmaceuticalisolators"] = 5, // Manufactured grade 5
        ["phasealloys"] = 3, // Manufactured grade 3
        ["phosphorus"] = 1, // Raw grade 1
        ["polonium"] = 4, // Raw grade 4
        ["polymercapacitors"] = 4, // Manufactured grade 4
        ["precipitatedalloys"] = 3, // Manufactured grade 3
        ["protoheatradiators"] = 5, // Manufactured grade 5
        ["protolightalloys"] = 4, // Manufactured grade 4
        ["protoradiolicalloys"] = 5, // Manufactured grade 5
        ["refinedfocuscrystals"] = 4, // Manufactured grade 4
        ["rhenium"] = 1, // Raw grade 1
        ["ruthenium"] = 4, // Raw grade 4
        ["salvagedalloys"] = 1, // Manufactured grade 1
        ["scanarchives"] = 2, // Encoded grade 2
        ["scandatabanks"] = 3, // Encoded grade 3
        ["scrambledemissiondata"] = 1, // Encoded grade 1
        ["securityfirmware"] = 4, // Encoded grade 4
        ["selenium"] = 4, // Raw grade 4
        ["shieldcyclerecordings"] = 1, // Encoded grade 1
        ["shielddensityreports"] = 3, // Encoded grade 3
        ["shieldemitters"] = 2, // Manufactured grade 2
        ["shieldfrequencydata"] = 5, // Encoded grade 5
        ["shieldingsensors"] = 3, // Manufactured grade 3
        ["shieldpatternanalysis"] = 4, // Encoded grade 4
        ["shieldsoakanalysis"] = 2, // Encoded grade 2
        ["sulphur"] = 1, // Raw grade 1
        ["symmetrickeys"] = 3, // Encoded grade 3
        ["technetium"] = 4, // Raw grade 4
        ["tellurium"] = 4, // Raw grade 4
        ["temperedalloys"] = 1, // Manufactured grade 1
        ["tg_abrasion03"] = 1, // Manufactured grade 1
        ["tg_biomechanicalconduits"] = 3, // Manufactured grade 3
        ["tg_causticcrystal"] = 4, // Manufactured grade 4
        ["tg_compositiondata"] = 3, // Encoded grade 3
        ["tg_propulsionelement"] = 5, // Manufactured grade 5
        ["tg_residuedata"] = 4, // Encoded grade 4
        ["tg_shipflightdata"] = 3, // Encoded grade 3
        ["tg_shipsystemsdata"] = 4, // Encoded grade 4
        ["tg_structuraldata"] = 2, // Encoded grade 2
        ["tg_weaponparts"] = 4, // Manufactured grade 4
        ["tg_wreckagecomponents"] = 3, // Manufactured grade 3
        ["thermicalloys"] = 4, // Manufactured grade 4
        ["tin"] = 3, // Raw grade 3
        ["tungsten"] = 3, // Raw grade 3
        ["uncutfocuscrystals"] = 2, // Manufactured grade 2
        ["unknowncarapace"] = 2, // Manufactured grade 2
        ["unknowncorechip"] = 5, // Manufactured grade 5
        ["unknownenergycell"] = 3, // Manufactured grade 3
        ["unknownenergysource"] = 5, // Manufactured grade 5
        ["unknownorganiccircuitry"] = 5, // Manufactured grade 5
        ["unknownshipsignature"] = 3, // Encoded grade 3
        ["unknowntechnologycomponents"] = 4, // Manufactured grade 4
        ["unknownwakedata"] = 4, // Encoded grade 4
        ["vanadium"] = 2, // Raw grade 2
        ["wakesolutions"] = 3, // Encoded grade 3
        ["wornshieldemitters"] = 1, // Manufactured grade 1
        ["yttrium"] = 4, // Raw grade 4
        ["zinc"] = 2, // Raw grade 2
        ["zirconium"] = 2, // Raw grade 2
    };
}
