namespace D47.Core.Journal;

/// <summary>
/// How many of a material a Commander can hold (list.md Phase 8, "Call out material-gathering
/// milestones").
/// <para>
/// <b>Elite reports capacity nowhere.</b> Not in a journal event, not in Status.json, not in the
/// <c>Materials</c> snapshot — the game simply stops accepting more. Capacity is set by the
/// material's grade, and the grade is not in the journal either. So the percentage milestones
/// need a table, and the only question was what kind.
/// </para>
/// <para>
/// A hand-written table of ~130 grades would be exactly the confidently-invented game data the
/// guardrails exist to prevent: a wrong entry surfaces as a milestone announced at the wrong
/// number, which is indistinguishable from the feature working correctly. The table in
/// <c>MaterialGrades.g.cs</c> is instead <b>derived</b> — generated by
/// <c>tools/gen-material-grades.py</c> from EDCD/FDevIDs, the canonical community id list that
/// Coriolis and EDEngineer are built on. It is checkable, refreshable, and traceable to
/// something that is not this file's author's memory.
/// </para>
/// <para>
/// The grade-to-capacity mapping lives here rather than in the generated file because it is a
/// fixed game rule about five numbers, not per-material data. It does not change when Frontier
/// adds a material, so regenerating the table must not be able to disturb it.
/// </para>
/// </summary>
public static partial class MaterialGrades
{
    /// <summary>
    /// The storage limit per grade: 300, 250, 200, 150, 100 for grades 1 through 5. A fixed
    /// game rule rather than something d47 derives, and deliberately not in the generated file.
    /// </summary>
    public static int? CapacityOfGrade(int grade) => grade switch
    {
        1 => 300,
        2 => 250,
        3 => 200,
        4 => 150,
        5 => 100,

        // Not a grade this rule covers. Answered as unknown rather than clamped to the nearest
        // one — a milestone at a made-up threshold is the failure this whole design avoids.
        _ => null,
    };

    /// <summary>The material's grade, or null for a name the table does not know.</summary>
    public static int? GradeOf(string? journalName) =>
        journalName is not null && ByName.TryGetValue(journalName, out var grade) ? grade : null;

    /// <summary>
    /// How many of this material can be held, or null when d47 does not recognise it.
    /// <para>
    /// Null is a correct answer, not a gap: a material added by a game update that d47's table
    /// predates has no known capacity, and the milestones stay silent for it rather than
    /// announcing a fraction of a number nobody checked. The first-unit milestone needs no
    /// capacity and keeps working either way.
    /// </para>
    /// </summary>
    public static int? CapacityOf(string? journalName) =>
        GradeOf(journalName) is { } grade ? CapacityOfGrade(grade) : null;

    /// <summary>How many materials the table knows. For the diagnostics surface and the tests.</summary>
    public static int Count => ByName.Count;
}
