using D47.Core.Knowledge;
using Xunit;

namespace D47.Core.Tests.Knowledge;

/// <summary>The generated rare goods table, and the one station each row names (#115).</summary>
public class ARareGoodHasOneStationToBeSoldAtTests
{
    [Fact]
    public void LavianBrandyIsSoldAtLaveStationInLave()
    {
        var lavianBrandy = RareCatalogue.Find("Lavian Brandy");

        Assert.NotNull(lavianBrandy);
        Assert.Equal("Lave", lavianBrandy.System);
        Assert.Equal("Lave Station", lavianBrandy.Station);
        Assert.Equal(128106744, lavianBrandy.MarketId);
    }

    [Fact]
    public void ARareGoodIsFoundByItsJournalSymbolToo()
    {
        var bySymbol = RareCatalogue.Find("lavianbrandy");
        var byName = RareCatalogue.Find("Lavian Brandy");

        Assert.NotNull(bySymbol);
        Assert.Equal(bySymbol, byName);
    }

    [Fact]
    public void EveryRareCargoMaterialHasARowHere()
    {
        var rareCargo = MaterialCatalogue.All.Where(entry => entry.Ledger == MaterialLedger.RareCargo);
        var known = RareCatalogue.All.Select(entry => entry.Symbol).ToHashSet(StringComparer.Ordinal);

        Assert.All(rareCargo, entry => Assert.Contains(entry.Symbol, known));
    }

    [Fact]
    public void EveryRowNamesASystemAndAStation()
    {
        Assert.True(RareCatalogue.All.Count > 100, $"{RareCatalogue.All.Count} rares");

        Assert.All(RareCatalogue.All, entry =>
        {
            Assert.False(string.IsNullOrWhiteSpace(entry.System));
            Assert.False(string.IsNullOrWhiteSpace(entry.Station));
            Assert.True(entry.MarketId > 0);
        });
    }

    [Fact]
    public void TheShippedTableCarriesTheGeneratorsHeader()
    {
        var text = File.ReadAllLines(Path.Combine(
            RepositoryRoot(), "src", "D47.Core", "Knowledge", "Rares.tsv"));

        Assert.Contains("# Generated by tools/gen-rares.py. Do not edit by hand — rerun the tool.", text);
        Assert.Contains(text, line => line.StartsWith("# Rows: ", StringComparison.Ordinal) &&
            line.Contains("Built: ", StringComparison.Ordinal));
    }

    private static string RepositoryRoot()
    {
        var at = new DirectoryInfo(AppContext.BaseDirectory);

        while (at is not null && !File.Exists(Path.Combine(at.FullName, "d47.slnx")))
        {
            at = at.Parent;
        }

        Assert.NotNull(at);
        return at!.FullName;
    }
}
