using D47.Core.Knowledge;
using Xunit;

namespace D47.Core.Tests.Knowledge;

/// <summary>The generated exobiology table, and what a body's own scan can predict from it (#204).</summary>
public class ASurveyedSpeciesIsPredictedFromItsBodysConditionsTests
{
    [Fact]
    public void ARockyBodyWithThinCarbonDioxideAndNoVolcanismIncludesBacteriumAurasus()
    {
        var possible = ExobiologyCatalogue.Possible(new BodyConditions
        {
            PlanetClass = "Rocky body",
            Atmosphere = "thin carbon dioxide atmosphere",
            Volcanism = "",
            Gravity = 0.2,
            Temperature = 200,
            Pressure = 0.02,
        });

        Assert.Contains(possible, entry => entry.Species == "Bacterium Aurasus");
    }

    [Fact]
    public void AnIcyBodyWithAHeliumAtmosphereExcludesBacteriumAurasus()
    {
        var possible = ExobiologyCatalogue.Possible(new BodyConditions
        {
            PlanetClass = "Icy body",
            Atmosphere = "thin helium atmosphere",
            Volcanism = "",
            Gravity = 0.2,
            Temperature = 200,
            Pressure = 0.02,
        });

        Assert.DoesNotContain(possible, entry => entry.Species == "Bacterium Aurasus");
    }

    /// <summary>
    /// The one fold shared between the generator and the catalogue: the journal's "sulfur" and Spansh's
    /// "Sulphur" meet at the same normalised word.
    /// </summary>
    [Fact]
    public void AJournalSulfurDioxideAtmosphereMatchesATableWrittenFromSpanshsSulphurSpelling()
    {
        var possible = ExobiologyCatalogue.Possible(new BodyConditions
        {
            PlanetClass = "Rocky body",
            Atmosphere = "thin sulfur dioxide atmosphere",
            Volcanism = "",
            Gravity = 0.35,
            Temperature = 200,
            Pressure = 0.02,
        });

        Assert.Contains(possible, entry => entry.Species == "Stratum Araneamus");
    }

    /// <summary>
    /// Frutexa Flammasis and Frutexa Flabellum admit the same conditions and differ only by region
    /// (#210).
    /// </summary>
    private static BodyConditions FrutexaConditions() => new()
    {
        PlanetClass = "Rocky body",
        Atmosphere = "ammonia atmosphere",
        Volcanism = "",
        Gravity = 0.1,
        Temperature = 160,
        Pressure = 0.002,
    };

    [Fact]
    public void ARegionExcludesASpeciesWhoseRegionsColumnLacksIt()
    {
        var possible = ExobiologyCatalogue.Possible(FrutexaConditions(), "Inner Scutum-Centaurus Arm");

        Assert.Contains(possible, entry => entry.Species == "Frutexa Flammasis");
        Assert.DoesNotContain(possible, entry => entry.Species == "Frutexa Flabellum");
    }

    [Fact]
    public void ANullRegionExcludesNothingOnRegion()
    {
        var possible = ExobiologyCatalogue.Possible(FrutexaConditions());

        Assert.Contains(possible, entry => entry.Species == "Frutexa Flammasis");
        Assert.Contains(possible, entry => entry.Species == "Frutexa Flabellum");
    }

    [Fact]
    public void EveryRowHasAGenusAPositiveValueAndARangeWhereLowIsNoHigherThanHigh()
    {
        Assert.True(ExobiologyCatalogue.All.Count > 100, $"{ExobiologyCatalogue.All.Count} species");

        Assert.All(ExobiologyCatalogue.All, entry =>
        {
            Assert.False(string.IsNullOrWhiteSpace(entry.Genus));
            Assert.True(entry.Value > 0);
            Assert.NotEmpty(entry.PlanetTypes);
            Assert.NotEmpty(entry.Atmospheres);
            Assert.True(entry.GravityLow <= entry.GravityHigh);
            Assert.True(entry.TemperatureLow <= entry.TemperatureHigh);
            Assert.True(entry.PressureLow <= entry.PressureHigh);
        });
    }

    [Fact]
    public void TheShippedTableCarriesTheGeneratorsHeader()
    {
        var text = File.ReadAllLines(
            Path.Combine(RepositoryRoot(), "src", "D47.Core", "Knowledge", "Exobiology.tsv"));

        Assert.Contains("# Generated by tools/gen-exobiology.py. Do not edit by hand — rerun the tool.", text);
    }

    private static string RepositoryRoot()
    {
        var at = new DirectoryInfo(AppContext.BaseDirectory);

        while (at is not null && !File.Exists(Path.Combine(at.FullName, "d47.slnx")))
        {
            at = at.Parent;
        }

        Assert.NotNull(at);
        return at!.FullName;
    }
}
